### ISSUE TITLE
What is the status of this project and other forks?

### ISSUE THREAD

**Issue by kytta** [sarnold/pystache#17]
If I understand correctly, Pystache started with https://github.com/defunkt/pystache. This repo claims to be the fork of it, but so does https://github.com/PennyDreadfulMTG/pystache. At the same time, the PyPI version release date doesn't match either your or @PennyDreadfulMTG's release dates on GitHub.

As such, I have the following questions:

1. Is the source of the PyPI this repository? If yes, why don't you tell others to download pystache from PyPI, but rather from GitHub's releases page?
2.  Who controls [pystache](https://pypi.org/project/pystache/) on PyPI? If it's you, why isn't the PyPI package linked here?
3. If you don't control the pystache package, could you reupload it to PyPI under a different name? Alternatively, could you ask @defunkt (or I guess it's @bakert) for the rights to continue publishing improvements under the old name?

@bakert @defunkt if you don't maintain your versions of pystache any more, could you please specify the current maintainer in the README and archive the repos?

**Comment by bakert** [comment]
The PyPi version is now https://github.com/PennyDreadfulMTG/pystache 

All of @sarnold's improvements have been incorporated there.

**Comment by kytta** [comment]
> The PyPi version is now https://github.com/PennyDreadfulMTG/pystache 

But it doesn't get published to PyPI, does it? The latest version on PyPI is 0.6.0. The latest GitHub release is 0.6.1. The latest Change log entry is 0.6.2.

I can see that publish step is disabled:
 https://github.com/PennyDreadfulMTG/pystache/blob/748b359a147111febbe188020dabab63862099d5/.github/workflows/release.yml#L107

Is there a reason for that?

The thing is, one can't depend on a non-PyPI package if one wants to get their package published to PyPI. That means, that any improvements you make to the parser are unavailable to those who use it as a dependency.

**Comment by bakert** [comment]
@kytta Thanks for your feedback. Although I'm 7 months late I've fixed this and now the repo, github releases and pypi all agree that 0.6.4 is our latest release.

**Comment by kytta** [comment]
> @kytta Thanks for your feedback. Although I'm 7 months late I've fixed this and now the repo, github releases and pypi all agree that 0.6.4 is our latest release.

It's never too late :) Thanks a lot!
